spring:
  application:
    name: yqx-backend
  # 默认 dev 环境
  # todo: 如需更换环境请更改此处
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  # todo: 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yqx_db?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  # Redis 配置
  # todo: 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: -1
      max-request-size: -1

# 又拍云
upyun:
  bucketName: jiusi
  userName: yqx
  password: xxx
  url: http://images.xxx.cc

server:
  port: 8866
  servlet:
    context-path: /api
mybatis:
  # 配置校验
  check-config-location: true
  # 配置实体类别名
  type-aliases-package: "cc.jiusi.springboot.init"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 转驼峰
    map-underscore-to-camel-case: true
  mapperLocations: classpath*:mappers/**/*Mapper.xml

# 邮箱配置
email:
  username: 10837907@qq.com
  password: xxx

# 讯飞星火配置
xunfei:
  client:
    appid: xxx
    apiSecret: xxx
    apiKey: xxx

# 生产环境屏蔽knif4j
knife4j:
  production: true
